services:
  api:
    build:
      context: services/platform/api
      dockerfile: Dockerfile
    volumes:
    - ./keys:/app/keys:ro
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JWT_PRIVATE_KEY_PATH: /app/keys/private.pem
      JWT_PUBLIC_KEY_PATH: /app/keys/public.pem
    ports:
      - "8080:8080"

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: services/platform/web
      dockerfile: Dockerfile

    volumes:
      - ./services/platform/web:/src
      - web_node_modules:/src/node_modules

    ports:
      - "4200:4200"

    restart: unless-stopped

  postgres:
    image: postgres:15

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 2s
      retries: 5


  rabbitmq:
    image: rabbitmq:4-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
  web_node_modules:
  # redis-data for later
