export const MetricDefinitionConstants = {
    NAME_MIN_LENGTH: 2,
    NAME_MAX_LENGTH: 50,

    DESCRIPTION_MIN_LENGTH: 2,
    DESCRIPTION_MAX_LENGTH: 100,

    INCOMING_FIELD_NAME_MIN_LENGTH: 2,
    INCOMING_FIELD_NAME_MAX_LENGTH: 100,

    UNIT_MAX_LENGTH: 25,

    DATA_TYPE_MAX_LENGTH: 20
}
