export const UserConstants = {
    FIRST_NAME_MIN_LENGTH: 2,
    FIRST_NAME_MAX_LENGTH: 50,

    LAST_NAME_MIN_LENGTH: 2,
    LAST_NAME_MAX_LENGTH: 50,

    EMAIL_MAX_LENGTH: 50,

    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 20,
}
